base_paths:
  default: /path/to/default/db/ # Overridden if database directory is passed in CLI to screen.

# Database configurations
databases:
  biorisk_hmm: 
    path: "{default}biorisk_db/biorisk.hmm"
  regulated_protein:
    protein_search_tool: "blastx" # Overrides CLI.
    blast:
      path: "{default}nr_blast/nr"
    diamond:
      path: "{default}nr_dmnd/nr.dmnd"
  regulated_nt:
    path: "{default}nt_blast/nt"
  benign:
    hmm:
      path: "{default}benign_db/benign.hmm"
    fasta:
      path: "{default}benign_db/benign.fasta"
    cm:
      path: "{default}benign_db/benign.cm"