name: commec-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10,<3.14
  # Runtime Python dependencies
  - biopython
  - numpy
  - pandas
  - pytaxonkit
  - pyyaml
  - pycountry
  # Runtime non-Python dependencies
  - blast>=2.17
  - hmmer
  - infernal
  - plotly
  - yaml
  - mako
  - wget
  - tar
  - zstd
  # Development dependencies
  - pip
  - pytest
  - matplotlib
  - pip:
      - -e .
