name: Test Commec

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ruff check
        uses: astral-sh/ruff-action@v4.1.0
        with:
          version: ">=0.15.10,<0.16.0"
      # Check ruff run, but do not fix
      # (format fixes in CI will exit 0 and then be lost to the codebase)
      name: Ruff isort
        run: ruff check --select I .
      - name: Ruff format
        run: ruff format --check --diff .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: commec-dev
          environment-file: environment.yaml
          auto-activate-base: false
          clean-patched-environment-file: true

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate commec-dev
          pytest -vv
